In [4]:
import numpy as np

A = np.linspace(1, 16, 16).reshape(4,4)

print(A)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]


In [6]:
v = np.array([0.5, 1, 2, 1])

v*A

array([[ 0.5,  2. ,  6. ,  4. ],
       [ 2.5,  6. , 14. ,  8. ],
       [ 4.5, 10. , 22. , 12. ],
       [ 6.5, 14. , 30. , 16. ]])

In [7]:
A*v

array([[ 0.5,  2. ,  6. ,  4. ],
       [ 2.5,  6. , 14. ,  8. ],
       [ 4.5, 10. , 22. , 12. ],
       [ 6.5, 14. , 30. , 16. ]])